config/routes.rb
    post 'edit_addr',:on=>:collection
    get 'departure_new',:on=>:collection
    post 'creat_addr',:on=>:collection
    get 'cart_goods',:on=>:collection
    get 'advance',:on=>:collection
    get 'choose_express',:on=>:collection
    get 'local_express',:on=>:collection
    post 'l_express',:on=>:collection
    get 'city',:on=>:collection
  end

  resources :tairyo do                   # #大渔饭店
    get   'index'  ,:on=>:collection
    get   'group'  ,:on=>:collection
    get   'tuangouxiang'  ,:on=>:collection
    get   'comment'  ,:on=>:collection
    get   'tese'  ,:on=>:collection
    get   'user'  ,:on=>:collection
    get   'map'  ,:on=>:collection
    get 'tairyo_comment' ,:on=>:collection
    get 'showorder' ,:on=>:collection
  end

  post 'users/tairyo' =>"users#tairyo_user" ,:controller=>"users"

  resources :coupons do
    get  'get',:on=>:member

    get 'comment_t'=>"comments#tairyo_comment",:controller=>"comments"
    post 'comment'=>"comments#tairyo",:controller=>"comments"

    get 'mycoupon'=>"coupon#mycoupon",  :controller=>"coupons"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"

  root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
  get 'blank'=>"home#blank"
  get 'home'=>"home#index"

  resources :pages, :only=>[:show,:index]

  namespace :auth do
    resources :accounts

    resources :email139 do
      get 'callback',:on=>:member
    end

    resources :weixin do
      get 'callback',:on=>:member

    end
    resources :weibo do
      get 'callback',:on=>:collection
    end
    resources :douban do
      get 'callback',:on=>:collection
    end
  end

  resources :sessions
  resources :users do
    get 'notice',:on=>:collection
    get 'forgot_password', :on=>:collection
    post 'send_reset_password_instruction', :on=>:collection
    get 'reset_password',:on=>:collection
    post 'search', :on=>:collection
    post 'change_password',:on=>:collection
  end

  resources :vshop do
    collection do
      get 'login'
      get 'register'
      get 'article'
      get 'apply'
      post 'search'
      post 'change_password'
      get 'goods'
      get 'orders'
      get 'members'
      get 'weixin'
      post "black_good_destory"
      post "destory"
      get "notice"
      get "clients"
      get "to_foodie"
    end
    member do
      get :user
      get :category
      get :commodity
      get :order
      get :payments
      get :native
      post :paynotifyurl
      get :paynotifyurl
      get :feedback
    end
=begin
    resources :payments do
      collection do
        get 'callback'
        get 'debug'
      end

      member do
        get 'pay'
        match ':adapter/notify'=>"payments#notify", :as=>"notify"
        match ':adapter/callback'=>"payments#callback", :as=>"callback"
        if Rails.env == 'development'
          get 'test_notify'
          get 'test_callback'
        end
      end
    end
=end
  end

  get 'auto_login'=>"sessions#auto_login"
  get 'auto_login2'=>"sessions#auto_login2"
  get 'shop_login'=>"sessions#shop_login"
  get 'autologin1'=>"sessions#auto_login1"
  get 'login'=>"sessions#new"
  get 'mlogin'=>"sessions#new_mobile"
  get 'mregister'=>"users#new_mobile"
  post 'login'=>"sessions#create"
  post 'mlogin'=>"sessions#create"
  get 'logout'=>"sessions#destroy"
  get 'topmenu'=>"home#topmenu"

  scope :module=> "events" do
    resources :user_survey, :controller=>"survey" do
      post "add_mobile", :on=>:collection

    end

  end

  namespace :events do
    resources :applicants

    resources :foodie do
      collection do
        get 'index'
        post 'add_foodie'
        get 'user_foodie'
        get 'detail'
      end
    end

    resources :party do
      collection do
        get 'index'
        get 'list'
        post 'stepone'
        get 'steptwo'
        post 'steptwo'
        get 'list'
        get 'user_party'
        get 'detail'
      end
    end

  end

  resources :events

  scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do
    resources :doctors do
      get :recommend_codes, :on=>:collection
    end

    resources :weihuos do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "downorder", :on=>:collection
      post "downgood", :on=>:collection
      put 'batch',:on=>:collection
      get "black_weihuo"   , :on=>:collection
      put "black_weihuo_edit" , :on=>:collection
      get "black_weihuo_new" , :on=>:collection
      post "black_weihuo_new" , :on=>:collection
      get 'select_all',:on=>:collection
      get 'search', :on=>:collection

      collection do
        get :goods
        get :organisations
        get :employees
        get :shops
        get :clients
        get :shares
        get :import
        get :downorder
        get :downgood
      end
    end

    get 'logout'=>'sessions#destroy'
    get 'get_users' => 'bonuses#get_users'
    get 'find_user' => 'bonuses#find_user'
    post 'send_bonus' => 'bonuses#send_bonus'
    resources :tracks do
      get :pages,:on=>:collection
    end

    resources :carts do

    end

    resource :rules do
      collection do
        get 'index'
      end
    end

    resource :tuans do
      collection do
        get 'index'
        put 'edit'
      end
    end

    resources :shops do
      collection do
        get 'detail'
      end
    end

    resources :wechat do
      get :menu,:on=>:collection
      get :menu_edit,:on=>:collection
      get :followers, :on=>:collection
      get :followers_import, :on=>:collection
      get :follower_renew,:on=> :collection
      get :groups, :on=>:collection
      get :batch_sending, :on=>:collection
      get :weixin,:on=>:collection
    end
    resources :resources
    resources :permissions do

    end
    resources :suppliers do
      get 'update_state',:on=>:collection
      get 'reco', :on => :member
    end

    resources :sessions
    resources :coupons
    resources :express_rules

    resources :goods_cats do
      get :create_top,:on=>:collection
      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
      post :save_top,:on=>:collection
    end
    resources :goods_types do
      put :updateType,:on=>:member
    end
    resources :goods_labels do
      put :updateLabel,:on=>:member
      get :createLabel,:on=>:collection
    end
    resources :brand_adms do
      get :delete
      put :update_brand,:on=>:member
    end
    resources :black_good do

    end

    resources :goods do
      get "black_good"   , :on=>:collection
      put "black_good_edit" , :on=>:collection
      get "black_good_new" , :on=>:collection
      post "black_good_new" , :on=>:collection
      get "tairyo_show",  :on=>:collection
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "remove_spec_item",:on=>:member
      get "add_spec_item",:on=>:member
      get "spec",:on=>:member
      put "update_spec",:on=>:member
      get 'select_goods',:on=>:collection
      get 'collocation',:on=>:member
      get 'set_suits',:on=>:member
      get 'cancel_suits',:on=>:member
      post 'create_collocation',:on=>:collection
      get 'search', :on=>:collection
      get 'select_gifts',:on=>:collection
      put 'batch',:on=>:collection
      get 'select_all',:on=>:collection

      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
    end
    resources :spec_items

    resources :images do
      post "mark", :on=>:collection
      post "rollback",:on=>:collection
      post "refresh",:on=>:collection
    end
    resources :articles do
      post 'set_position',:on=>:collection
    end
    resources :topics do
      post 'set_position',:on=>:collection
      post 'published_at',:on=>:member
    end
    resources :pages

    resources :members do
      post "export",:on=>:collection
      post "column_reload",:on=>:collection
      post "send_sms",:on=>:collection
      post "send_sms2",:on=>:collection
      get :info,:on=>:member
      put :updateInfo,:on=>:member
    end

    resources :cards do
      get 'buy',:on=>:member
      get 'use',:on=>:member
      get 'edit_user',:on=>:member
      get 'edit_pay',:on=>:member
      get 'logs', :on=>:member
      post 'import', :on=>:collection
      post "export",:on=>:collection
      get "tag",:on=>:collection
      put "untag",:on=>:member
      put "cancel_order",:on=>:member
    end

    resources :users do
      get 'search',:on=>:collection
      post 'newuser',:on=>:collection
      put 'send_sms_code',:on=>:member
      put 'buy_card',:on=>:member
      put 'use_card',:on=>:collection
      get 'select', :on=>:member
      put 'validate_mobile',:on=>:member
    end
    resources :member_cards

    resources :tag_exts

    resources :configs

    resources :labels

    resources :emails do
      get 'send_all',:on=>:collection
    end

    resources :categories

    resources :applicants

    resources :events do
      get 'applicants',:on=>:member
    end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  include Admin::SessionsHelper
	def index
		@events  = Imodec::Event.paginate(:page => params[:page], :per_page => 20,:order=>"created_at desc")
	end

	def new
		@create_or_update_path = admin_events_path
		@event = Imodec::Event.new
	end

	def show
		@event = Imodec::Event.find(params[:id])
		# @applicants = @event.applicants
	end

	def applicants
		@event = Imodec::Event.find(params[:id])
		@applicants = @event.applicants.paginate(:page => params[:page], :per_page => 20,:order=>"created_at desc")
	end
	
	def edit

		@event = Imodec::Event.find(params[:id])
		@create_or_update_path = admin_event_path(@event)
	end

	def create
		@event = Imodec::Event.new(params[:imodec_event]) do |ev|
    ev.startime= Time.parse(params[:imodec_event][:startime]).to_i
    ev.endtime= Time.parse(params[:imodec_event][:endtime]).to_i
      end
		if @event.save
			redirect_to edit_admin_event_url(@event)
		else
			render "new"
		end

	end

	def update
		@event = Imodec::Event.find(params[:id])
    startime=params[:imodec_event].delete(:startime)
    endtime= params[:imodec_event].delete(:endtime)
    startime= Time.parse(startime).to_i
    endtime= Time.parse(endtime).to_i

		if @event.update_attributes(params[:imodec_event].merge!(:startime=>startime,:endtime=>endtime))
    redirect_to edit_admin_event_url(@event)
		else
			render action: "edit"
		end
	end

	def destroy
		@event = Imodec::Event.find(params[:id])
    		@event.destroy

	      respond_to do |format|
	        format.html { redirect_to admin_events_url }
	        format.json { head :no_content }
	      end
	end
end

app/controllers/events/applicants_controller.rb
class Events::ApplicantsController < ApplicationController
  layout  nil
  def create
  	@applicant = Imodec::Applicant.new(params[:applicant])
  	
  	if @applicant.save
  		render "create"
	else
		render "error"
	end
  end

end

app/controllers/events/foodie_controller.rb
class Events::FoodieController < ApplicationController
  layout "tradev"
  def index
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @events  = Imodec::Event.paginate(:page => params[:page], :conditions =>{:terminal=>"mobile",},:per_page => 20,:order=>"endtime desc")
    @events =@events.where("endtime>UNIX_TIMESTAMP(now()) ")
  end

  def new
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @event= Imodec::Event.find(params[:id])
    @applicants = @event.applicants.paginate(:page => params[:page], :per_page => 20,:order=>"created_at desc")

    @action_url="/events/foodie/add_foodie"
    render :layout => "default"
  end

  def add_foodie
    member_id =0
    if @user
      member_id = @user.member_id
    end

    if params[:applicant][:event_id]=='8'
      params[:applicant].merge!(:user_desc=>params[:applicant].delete(:address))
      @applicant = Imodec::Applicant.where(:email=>params[:applicant][:email],:mobile=>params[:applicant][:mobile])

      if @applicant.size==0
        @applicant = Imodec::Applicant.new(params[:applicant])
        @applicant.save
      end
     return redirect_to "/events/party/detail?id=8&supplier_id=78#applicants"
    else
      @user.update_attributes(:user_desc=>params[:user_desc])
    end
    

    @applicant = Imodec::Applicant.new(params[:applicant])
    @app= Imodec::Applicant.where(:member_id=>member_id,:event_id=>@applicant.event_id)
     if @app.size>0
       render "error"
     else

       if @applicant.save
         render "create"
       else
         render "error"
       end
     end
  end


  def user_foodie
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @applicant = Imodec::Applicant.where(:member_id=>@user.member_id).order("created_at desc")

  end


  def detail
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
  end


  end

app/controllers/events/party_controller.rb
#encoding:utf-8
class Events::PartyController < ApplicationController
  layout "tradev"

  def index
    if @user
      @supplier=Ecstore::Supplier.find(params[:supplier_id])
      render :layout => "default"    
    end

  end

  def stepone
    @users=Ecstore::User.where(:member_id=>@user.member_id).first
     if @users.update_attributes(params[:user])

     end
    redirect_to "/events/party?supplier_id=78&step=2"
  end

  def steptwo
    @event = Imodec::Event.new(params[:event]) do |ev|
       ev.startime= Time.parse(params[:event][:startime]).to_i
       ev.endtime= Time.parse(params[:event][:endtime]).to_i
    end



     if @event.save
       redirect_to "/events/party?supplier_id=78&step=3"
     end
   end

  def list
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @events  = Imodec::Event.paginate(:page => params[:page], :per_page => 20,:order=>"endtime desc")
  end

  def user_party
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @events  = Imodec::Event.paginate(:page => params[:page], :per_page => 20,:order=>"endtime desc",:conditions =>{
        :terminal=>"mobile",:member_id=>@user.member_id})
  end


  def detail
    if params[:id]=='11'
      return redirect_to "/hat/"
    end
    @supplier=Ecstore::Supplier.find(params[:supplier_id])
    @event = Imodec::Event.find(params[:id])
    @applicants = @event.applicants.paginate(:page => params[:page], :per_page => 20,:order=>"created_at desc")
    @event_desc=@event.name
    #塞浦路斯
    if params[:id]=='8'
      render :layout=>"cyprus"
    end
  end

end

app/controllers/events/survey_controller.rb
#encoding:utf-8
class Events::SurveyController < ApplicationController
	include Wicked::Wizard


	protect_from_forgery
	
	before_filter :authorize_survey!
	# skip_before_filter :authorize_user!

	steps :start, :i_like_coupon, :go_to_salon,:type_your_mobile

	def show
		render_wizard
	end

	def add_mobile
		if @user.update_attributes(:mobile=>params[:survey][:mobile])
			case params[:survey][:gift]
				when "coupon"
					@user.receive_register_gift("100元抵用券")
					@user.receive_new_coupon
				when "salon"
					@user.receive_register_gift("参与VIP沙龙活动")
			end

			render "completed"
			session.delete("from")
		else
			render "error"
		end
	end


	def update
		case step
	 	      when :i_like_coupon
	 	      		@gift = "coupon"
	 	      		
	 	      		@user.receive_register_gift("100元抵用券")
	 	      		@user.receive_new_coupon
	 	      		render "completed"

	 	      		# if @user.mobile.present?
	 	      		# 	@user.receive_register_gift("100元抵用券")
	 	      		# 	@user.receive_coupon
	 	      		# 	render "completed"
	 	      		# else
	 	      		# 	render "show_mobile"
	 	      		# end

			when :go_to_salon
				@gift = "salon"
				if @user.mobile.present?
					@user.receive_register_gift("参与VIP沙龙活动")
					render "completed"
				else
					render "show_mobile"
				end
		end
	end

	private
  		def finish_survey_path
  			# if session[:from] == "external_auth"
			# 	return "/trust-post_login.html"
			# end

			refer_url = cookies[:unlogin_url]
			if refer_url&& refer_url.present?
				cookies.delete(:unlogin_url)
				refer_url
			else
				"http://#{request.server_name}:#{request.server_port}"
			end
  		end

  		def authorize_survey!
  			@finish_survey_path = finish_survey_path
  			# return @user = Ecstore::User.find_by_name("yangxiaofei")
  			@coupon = Ecstore::NewCoupon.where(:coupon_prefix=>"B0001").first
  			return redirect_to(finish_survey_path) if @coupon&&!@coupon.enable?
  			@user  =  current_account.user
  			return redirect_to(finish_survey_path) if @user&&@user.has_received_gift?
  		end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	# layout 'event'
	layout 'magazine'

	def show
		@event =  Imodec::Event.find(params[:id])
	end
end

app/helpers/events/applicants_helper.rb
module Events::ApplicantsHelper
end

app/helpers/events/survey_helper.rb
module Events::SurveyHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<link href="/assets/jquery.ui.core.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/jquery.ui.theme.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/jquery.ui.datepicker.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<link href="/assets/admin/promotions.css?body=1" media="screen" rel="stylesheet" type="text/css" />
<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.ui.core.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.ui.datepicker.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery-ui-timepicker-addon.js?body=1" type="text/javascript"></script>
<script src="/assets/jquery.ui.datepicker-zh-CN.js?body=1" type="text/javascript"></script>
<script src="/assets/admin/promotions.js?body=1" type="text/javascript"></script>

<%= form_for @event,:url=>@create_or_update_path ,:html => {:class => "form-horizontal eventform"} do |f| %>
  <%if @event.member_id.nil?%>
    <%=f.hidden_field :member_id ,:value=>"2521"%>
        <%end%>
  <% if @event.errors.any? %>
      <div class="notice">
        <ul>
        <% @event.errors.messages.each do |key,msg| %>
          <li><%= msg.join(",") %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <fieldset>
    <div class="control-group">
      <%= f.label :name, "活动名称", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :name, :placeholder => "活动名称" %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :times, "报名截止时间", :class => "control-label" %>
      <div class="controls">
            <%unless @event.endtime.nil?%>
        <%=f.text_field :endtime,:value=>Time.at(@event.endtime).to_s(:db),:class=>"span2 datetime" %>
            <%else%>
        <%=f.text_field :endtime,:class=>"span2 datetime"%>
        <%end%>
           </div>
    </div>
    <div class="control-group">
      <%= f.label :startime, "请选择活动开始时间", :class => "control-label" %>
      <div class="controls">
        <%unless @event.startime.nil?%>
        <%=f.text_field :startime,:value=>Time.at(@event.startime).to_s(:db),:class=>"span2 datetime"%>
        <%else%>
            <%=f.text_field :startime,:class=>"span2 datetime"%>
        <%end%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :adds, "活动地点", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :adds, :placeholder => "活动地点" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :terminal, "活动展示", :class => "control-label" %>
      <div class="controls">
        <%=f.select :terminal, {"电脑端"=>"pc","手机端"=>"mobile" }%>
      <span style="color: red">pc端显示的是pc的页面以及活动</span>
      </div>
    </div>


    <div class="control-group">
      <%= f.label :body, "内容", :class => "control-label" %>
      <div class="controls">
        <%= f.cktext_area :body, :toolbar => 'Easy',:language=>'zh-cn',:height => 300 %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <input type="button" value="确定" class="btn btn-primary submit">

        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to '返回', admin_events_path %>
      </div>
    </div>
  </fieldset>
<% end %>


<script>
    $(document).ready(function(){


        $(".submit").click(function(){
            var startime=$("#imodec_event_startime").val();
            var endtime=$("#imodec_event_endtime").val();

            if( new Date(endtime)> new Date(startime)){
///               alert("报名截至时间不能大于活动开始时间"); return false;
            }

            var event_name=$("#imodec_event_name").val();
            var event_adds=$("#imodec_event_adds").val();
            var event_times=$("#imodec_event_times").val();
            if (event_name==""||event_adds==""||event_times=="") {
                alert("信息量不足!无法发布活动哦!");
                return false;
            }
            else{
                $(".eventform").submit();
            }
        })
    })


</script>

app/views/admin/events/applicants.html.erb
  <h4>
    <b><%=@event.name%></b>
    报名者(<%=@applicants.size%>)
  </h4>

<table class="table table-bordered table-hover">
  <tr>
    <th>姓名</th>
    <th>性别</th>
    <th>年龄</th>
    <th>手机</th>
    <th>微信号</th>
    <th>邮箱</th>
    <th>报名时间</th>
  </tr>

<% @applicants.each do |applicant| %>
  <tr>
    <td><%=applicant.name%></td>
    <td><%=applicant.sex%></td>
    <td><%=applicant.age%></td>
    <td><%=applicant.mobile%></td>
    <td><%=applicant.wechat_num%></td>
    <td><%=applicant.email%></td>
    <td><%=applicant.created_at%></td>
  </tr>
<% end %>
</table>

<div class="pagination">
  <%= will_paginate @applicants, :container => false if @applicants.size > 0%>
</div>

app/views/admin/events/edit.html.erb
<%=render "form"%>

app/views/admin/events/index.html.erb
<div class="page-header">
  <h2>所有吃货帮活动
    <%= link_to '新建活动', new_admin_event_path, :class => "pull-right btn btn-primary" %>
  </h2>

</div>

<table class="table table-bordered table-hover">
  <tr>
    <th>活动名</th>
    <!-- <th>活动时间</th> -->
    <th>创建时间</th>
    <th>终端</th>
    <th></th>
  </tr>

<% @events.each do |event| %>
  <tr>
    <td><%=event.name%></td>
    <td><%=event.created_at%></td>
    <td><%=event.terminal_text%></td>
    <td><%= link_to '查看', event_path(event),:target=>"_blank" %></td>
    <td><%= link_to '查看报名者', applicants_admin_event_path(event) %></td>
    <td><%= link_to '编辑', edit_admin_event_path(event) %></td>
    <td><%= link_to '删除', admin_event_path(event), method: :delete, data: { confirm: '确定删除吗?' } %></td>
  </tr>
<% end %>
</table>

<div class="pagination">
  <%= will_paginate @events, :container => false %>
</div>

app/views/admin/events/new.html.erb
<%=render "form"%>