config/routes.rb
require 'httpclient'
Modengke::Application.routes.draw do

post 'temp_info_api' => 'weihuo/weixin_pay#temp_info_api'
post 'foodie_notify_url' => 'foodies#foodie_notify_url'
post 'send_group_message_api' => 'weihuo/weixin_pay#send_group_message_api'
get 'foodies/foodie_pay' => 'foodies#foodie_pay'
get 'foodies/foodie_group_share' => 'foodies#foodie_group_share'

get 'foodies/go_to_foodie_from_share' => 'foodies#go_to_foodie_from_share'
  namespace :weihuo do
    get 'pay_with_goods' => 'weixin_pay#pay_with_goods'
    get 'qrcode' => 'weixin_pay#qrcode'
    get 'test_qrcode' => 'weixin_pay#test_qrcode'
    post 'notify_page' => 'weixin_pay#notify_page'
    post 'template_information' => 'weixin_pay#template_information'
    get 'shops/add' => 'shops#add'
    post 'shops/goods_added' => 'shops#goods_added'
    get 'goods_detail/:id' => 'shops#goods_detail'
    get 'shops/share' => 'shops#share'
    get 'shops/manage' => 'shops#manage'
    get 'shops/show_members' => 'shops#show_members'
    get 'shops/member_detail' => 'shops#member_detail'
    get 'shops/show_bonuses' => 'shops#show_bonuses'
    get 'shops/show_goods' => 'shops#show_goods'
    get 'shops/show_notice' => 'shops#show_notice'
    get 'shops/user_center' => 'shops#user_center'
    get 'shops/using_guide' => 'shops#using_guide'
    get 'shops/my_orders' => 'shops#my_orders'
    get 'shops/my_addresses' => 'shops#my_addresses'
    get 'shops/show_orders' => 'shops#show_orders'
    get 'shops/order_detail' => 'shops#order_detail'
    post 'shops/modify_ship_status' => 'shops#modify_ship_status'
    get 'shops/show_qrcode' => 'shops#show_qrcode'
    get 'shops/bonus_detail' => 'shops#bonus_detail'
    get 'shops/my_visited_shops' => 'shops#my_visited_shops'

    resources :orgnizations
    resources :orders

    resources :shops do
      collection do
        get :gallery
        get :admin
        get :admin_visitors
        get :admin_orders
        get :user_center
        get :categories
        get :orderlist
        get :brand
        get :mobile_search

      end

      member do
        get :shop
        get :category_goods
      end
    end
  end

  resources :mobile do
  	collection do
  		get :gallery
      get :share
      get :belongs
      get :belongs_order
      get :admin
      get :admin_visitors
      get :admin_orders
      get :user_center
      get :categories
      get :orderlist
      get :mobile_search

  	end

    member do
      get :shop
      get :category_goods
      get :cates
    end
  end

  resources :distributions do

    collection do
      get :cart
      get :bookmark
      get :orderproducts
      get :ordernew
    end

    member do
      get 'add_to_cart'
      get :product
      get :add_to_bookmark
      get :category
    end
  end

  get 'shop'=>'shop/shopinfos#myshop'
  namespace :shop do

    resource :shopinfos do
      member do
        get 'index'
        get 'show_goods'
        post 'add_goods'
        get 'adderror'
        get 'my_goods'
        get 'goods_details'
        get :myshop
        get :goods_destroy
        post 'goods_destroy'
        get 'myorder'
        get 'details_trade'
        post "fendian"
        delete 'delete_order'
      end
    end

    resource :shopusers do
      collection do
        get "index"
        get "clients"
        get "share"
        get "branch"
        get "user"
        post "edit"
        get "delete"
        post "submit_delete"
      end
    end

    resource :visitors do
      collection do
        get 'istrue'
        post 'my_add_shopping'
        get 'my_shopping_cart'
        get 'order_clearing'
        get 'order_show'
      end
    end
  end

  resources :commissions do
    collection do
      get  'platform'
      get 'bank_info'
    end

    member do
      get 'paid'
    end
  end

  resources :manco do
    get 'manco_comment'  ,:on=>:collection
    get   'index'  ,:on=>:collection
    get 'map' ,:on=>:collection
    get  'main' ,:on=>:collection    ###万家介绍
    get  'history' ,:on=>:collection  ####万家历史
    post 'blackboardfind_e',:on=>:collection  ###查询运价
    get  'user'   ,:on=>:collection
    post 'mancoluodipei',:on=>:collection
    get 'find_manco',:on=>:collection
    get "black_index"  ,:on=>:collection   ##小黑版首页
    get "express"  ,:on=>:collection
    post "serach"  ,:on=>:collection
    get "blackbord",:on=>:collection
    post "blackbord_add" ,:on=>:collection
    get "follow",:on=>:collection    ###快递跟踪
    post "follow",:on=>:collection    ###快递跟踪
    get 'user',:on=>:collection
    get 'good_source', :on=>:collection  ###货源信息
    post 'blackgood_add',:on=>:collection
    get 'black_good_index' ,:on=>:collection
    get 'show_carblack',:on=>:collection
    get 'departure' ,:on=>:collection
    post 'departure_edit',:on=>:collection
    post 'edit_addr',:on=>:collection
    get 'departure_new',:on=>:collection
    post 'creat_addr',:on=>:collection
    get 'cart_goods',:on=>:collection
    get 'advance',:on=>:collection
    get 'choose_express',:on=>:collection
    get 'local_express',:on=>:collection
    post 'l_express',:on=>:collection
    get 'city',:on=>:collection
  end

  resources :tairyo do                   # #大渔饭店
    get   'index'  ,:on=>:collection
    get   'group'  ,:on=>:collection
    get   'tuangouxiang'  ,:on=>:collection
    get   'comment'  ,:on=>:collection
    get   'tese'  ,:on=>:collection
    get   'user'  ,:on=>:collection
    get   'map'  ,:on=>:collection
    get 'tairyo_comment' ,:on=>:collection
    get 'showorder' ,:on=>:collection
  end

  post 'users/tairyo' =>"users#tairyo_user" ,:controller=>"users"

  resources :coupons do
    get  'get',:on=>:member

    get 'comment_t'=>"comments#tairyo_comment",:controller=>"comments"
    post 'comment'=>"comments#tairyo",:controller=>"comments"

    get 'mycoupon'=>"coupon#mycoupon",  :controller=>"coupons"
  end

  mount WeixinRailsMiddleware::Engine, at: "/"

  root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
  get 'blank'=>"home#blank"
  get 'home'=>"home#index"

  resources :pages, :only=>[:show,:index]

  namespace :auth do
    resources :accounts

    resources :email139 do
      get 'callback',:on=>:member
    end

    resources :weixin do
      get 'callback',:on=>:member

    end
    resources :weibo do
      get 'callback',:on=>:collection
    end
    resources :douban do
      get 'callback',:on=>:collection
    end
  end

  resources :sessions
  resources :users do
    get 'notice',:on=>:collection
    get 'forgot_password', :on=>:collection
    post 'send_reset_password_instruction', :on=>:collection
    get 'reset_password',:on=>:collection
    post 'search', :on=>:collection
    post 'change_password',:on=>:collection
  end

  resources :vshop do
    collection do
      get 'login'
      get 'register'
      get 'article'
      get 'apply'
      post 'search'
      post 'change_password'
      get 'goods'
      get 'orders'
      get 'members'
      get 'weixin'
      post "black_good_destory"
      post "destory"
      get "notice"
      get "clients"
      get "to_foodie"
    end
    member do
      get :user
      get :category
      get :commodity
      get :order
      get :payments
      get :native
      post :paynotifyurl
      get :paynotifyurl
      get :feedback
    end
=begin
    resources :payments do
      collection do
        get 'callback'
        get 'debug'
      end

      member do
        get 'pay'
        match ':adapter/notify'=>"payments#notify", :as=>"notify"
        match ':adapter/callback'=>"payments#callback", :as=>"callback"
        if Rails.env == 'development'
          get 'test_notify'
          get 'test_callback'
        end
      end
    end
=end
  end

  get 'auto_login'=>"sessions#auto_login"
  get 'auto_login2'=>"sessions#auto_login2"
  get 'shop_login'=>"sessions#shop_login"
  get 'autologin1'=>"sessions#auto_login1"
  get 'login'=>"sessions#new"
  get 'mlogin'=>"sessions#new_mobile"
  get 'mregister'=>"users#new_mobile"
  post 'login'=>"sessions#create"
  post 'mlogin'=>"sessions#create"
  get 'logout'=>"sessions#destroy"
  get 'topmenu'=>"home#topmenu"

  scope :module=> "events" do
    resources :user_survey, :controller=>"survey" do
      post "add_mobile", :on=>:collection

    end

  end

  namespace :events do
    resources :applicants

    resources :foodie do
      collection do
        get 'index'
        post 'add_foodie'
        get 'user_foodie'
        get 'detail'
      end
    end

    resources :party do
      collection do
        get 'index'
        get 'list'
        post 'stepone'
        get 'steptwo'
        post 'steptwo'
        get 'list'
        get 'user_party'
        get 'detail'
      end
    end

  end

  resources :events

  scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do
    resources :doctors do
      get :recommend_codes, :on=>:collection
    end

    resources :weihuos do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "downorder", :on=>:collection

app/controllers/weihuo/orders_controller.rb
#encoding:utf-8

class Weihuo::OrdersController < ApplicationController

  layout "weihuo"

  def index

    
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end
  
end

app/helpers/admin/orders_helper.rb
#encoding:utf-8
module Admin::OrdersHelper
	def payment_options
		{
#		"bcom"=>"交通银行在线支付",
#		"icbc"=>"工商银行在线支付",		
#		"99bill"=>"快钱网上支付",
		"deposit"=>"预存款支付",
		"offline"=>"货到付款",
		"alipay"=>"支付宝支付",
		"wxpay"=>"微信支付",
		"alipaywap"=>"支付宝手机版",
    	"ips"=>"环迅人民币支付"}
	end
end

app/helpers/store/orders_helper.rb
#encoding:utf-8
module Store::OrdersHelper

	def ship_day_options
		{      "任意日期"=>"任意日期",
			"仅工作日"=>"仅工作日",
			"仅休息日"=>"仅休息日",
			"指定日期"=>"special"  }
	end

	def ship_time_options
		{     "任意时间段"=>"任意时间段",
			"上午"=>"上午",
			"下午"=>"下午",
			"晚上"=>"晚上"  }
	end


	def payments
		{
      "term"=>{ :name=>"账期支付",:extra=>"与供应商协商"},
      "ips"=>{ :name=>"环迅人民币支付",:extra=>""},
			"bcom"=>{ :name=>"交通银行网上支付", :extra=>"持交通银行卡在线支付可享受订单金额95折优惠" },
			"icbc"=>{ :name=>"工商银行网上支付", :extra=>'申请分期付款 (<span class="highlight">申请信用卡分期付款，超低手续费，月还款无压力！</span>)' },
			"deposit"=>{ :name=>"预存款", :extra=>"" },
			"offline"=>{ :name=>"货到付款", :extra=>link_to("点击查询货到付款配送区域","http://www.zjs.com.cn/WS_Business/WS_Bussiness_CityArea.aspx?id=6",:target=>"_blank").html_safe }, 
			"99bill"=>{ :name=>"其他银行网上支付",:extra=>"" },
			"alipay"=>{ :name=>"支付宝",:extra=>"" },
      "alipaywap"=>{ :name=>"支付宝手机版",:extra=>"" },
      "wxpay"=>{:name=>"微信支付",:extra=>""}
		}
	end
end

app/views/admin/orders/_filter.html.erb
<%=form_for :s,:url=>search_admin_orders_path,:method=>:get,:html=>{:class=>"form-search"} do |f|%>
<%=f.text_field :q, :value=>params[:s]&&params[:s][:q],:placeholder=>"订单号/收货人"%>
<input type="submit" value="搜索" class="btn btn-success">
<%=link_to "清除",admin_orders_path,:class=>"btn"%>
<%end%>

app/views/admin/orders/_modal.html.erb
<div class="modal hide fade" id="ajax_modal">
  <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4>支付</h4>
  </div>

  <div class="modal-body">
      
  </div>

  <div class="modal-footer">
    <!-- <a href="#" class="btn" data-dismiss="modal">关闭</a> -->
    <!-- <a href="#" class="btn btn-primary">提交</a> -->
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $(".remote-modal").click(function(){
        var modal = $(this).data("target");
        var remote_url = $(this).data("remote");
        $(modal).modal().on("show",function(){
            $(this).find(".modal-body").empty();
        }).on("shown",function(){
             $(this).find(".modal-body").load(remote_url);
        });
        return false;
    });
  });
</script>

app/views/admin/orders/_order_tr.html.erb
<% if order.status == 'active' && order.pay_status == '1' && order.ship_status == '1' %>
<% conditions = 'warning' %>
<% elsif order.status == 'finish' %>
<% conditions = 'success' %>
<% end %>
<tr class="<%=order.status%> <%= conditions %>" id="order_<%=order.order_id%>">
	<td>
		<%= check_box_tag nil, order.order_id, false,:id=>"check_#{order.order_id}",:class=>"order"%>
	</td>
	<td><%=order.order_id%></td>

	<td><%=link_to "详细",detail_admin_order_path(order),:target=>"_blank"%></td>
	<%if current_admin.has_right_of("orders","delivery")%>
	<td class="dropdown">
		<%if order.status == "active"%>
		<%=link_to "#",:class=>"dropdown-toggle",:data=>{:toggle=>"dropdown"} do%>
		订单操作 <b class="caret"></b>
		<%end%>
		<ul class="dropdown-menu">
			<!-- <li><%=link_to "编辑",edit_admin_order_path(order),:target=>"_blank" if order.status == 'active'%></li> -->

			<li>
				<%=link_to "支付",pay_admin_order_path(order,:page=>params[:page]) if order.pay_status == '0'%>

				<%link_to "支付",pay_admin_order_path(order,:page=>params[:page]),:data=>{:target=>"#ajax_modal",:remote=>pay_admin_order_path(order) },:class=>"remote-modal" if order.pay_status == '0'%>
			</li>

			<li><%=link_to "退款", refund_admin_order_path(order,:page=>params[:page]) unless %w(0 5).include?(order.pay_status)%></li>

			<li><%=link_to "发货",delivery_admin_order_path(order,:page=>params[:page]) if ['0','2'].include?(order.ship_status)%></li>

			<li>
				<%=link_to "退货",reship_admin_order_path(order,:page=>params[:page]) if !['0','4'].include?(order.ship_status)%>
			</li>

			<li><%=link_to "完成",admin_order_path(order,:order=>{:status=>'finish'}),:method=>:put,:remote=>true,:confirm=>"完成操作会将该订单归档并且不允许再做任何操作，确认要执行吗?" if order.status == 'active'%></li>
			<li><%=link_to "作废",admin_order_path(order,:order=>{:status=>'dead'}),:method=>:put,:remote=>true,:confirm=>"作废后该订单将不能做任何操作，确认要执行吗?" if order.status == 'active'%></li>
			<li>
				<%=link_to "订单备注",comment_admin_order_path(order,:page=>params[:page])%>
			</li>
			<li>
				<%= link_to '删除', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>
			</li>
		</ul>
		<%end%>
	</td>
	<td>
		<%=link_to "购", print_order_admin_order_path(order),:target=>"_blank"%>
		<%=link_to "配", print_preparer_admin_order_path(order),:target=>"_blank"%>
	</td>
	<%end%>
	<td>
		<%order.tegs.each do |teg|%>
		<span class="teg" style="background-color:<%=teg.tag_bgcolor%>;color:<%=teg.tag_fgcolor%>">
			<%=teg.tag_name%>
		</span>
		<%end%>
	</td>
	<td><%=order.member_id if order.user%></td>
	<td><%=order.created_at%></td>
	<td><%=order.payment_name%></td>
	<td><%=order.status_text%></td>
	<td><%=order.pay_status_text%></td>
	<td><%=order.ship_status_text%></td>
	<td><%=number_to_currency order.final_amount,:unit=>"&yen;",:precision=>2%></td>
	<td><%=number_to_currency order.share_for_promotion,:unit=>"&yen;",:precision=>2%></td>
	<td><%=order.ship_name%></td>
	<td><%=order.ship_addr%></td>
	<td><%=order.ship_mobile%></td>
	<td><%=order.member.name if order.promotion_id%></td>
</tr>
<% if @total_commission.present? && @total.present? %>
<%@total_commission +=order.share_for_promotion%>
<%@total +=order.final_amount%>
<% end %>

app/views/admin/orders/_pay_form.html.erb
<%=form_for :payment, :url=>dopay_admin_order_path(@order,:return_url=>@return_url), :html=>{ :class=>"form-horizontal" } do |f|%>

  <div class="control-group">
    <label class="control-label">订单号:</label>
    <div class="controls">
     	<span class="readonly-field"><%=@order.order_id%> (<%=@order.pay_status_text%>)</span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">会员:</label>
    <div class="controls">
     	<span class="readonly-field"><%=@order.user.login_name if @order.user%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">订单金额:</label>
    <div class="controls">
     	<span class="readonly-field">&yen;<%=@order.final_amount.to_i%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">已收金额:</label>
    <div class="controls">
     	<span class="readonly-field">&yen;<%=@order.part_pay.to_i%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">收款金额:</label>
    <div class="controls">
     	<%=f.number_field :money,:value=>@order.final_amount,:class=>"input-small"%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label">支付方式:</label>
    <div class="controls">
     	<select class="span2" id="payment_pay_app_id" name="payment[pay_app_id]">
     		<option value="">请选择</option>
     		<%payment_options.each do |value,text|%>
		<option value="<%=value%>" <%='selected' if value == @order.payment%> ><%=text%></option>
		<%end%>
	</select>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">交易号:</label>
    <div class="controls">
     	<%=f.text_field :trade_no%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label">付款人:</label>
    <div class="controls">
     	<%=f.text_field :pay_account%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">备注:</label>
    <div class="controls">
     	<%=f.text_field :memo,:class=>"span4"%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
     	<%=f.submit "提交",:class=>"btn btn-primary" if @order.pay_status == '0'%>
     	<a href="<%=@return_url%>" class="btn" data-dismiss="modal">取消</a>
    </div>
  </div>
  

<%end%>

app/views/admin/orders/comment.html.erb
<%= form_for @order,:url => update_memo_admin_order_path, :html => {:class => "form-horizontal"} do |f| %>
  
  <fieldset>
    <div class="control-group">
      <%= f.label :order_id, "订单号", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :order_id,:readonly=>true%>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :memo, "订单备注", :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :memo%>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
        <%= f.submit '确定', :class => "btn btn-primary" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '返回', admin_orders_path %>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/admin/orders/dopay.js.erb
alert('付款成功');
$('#ajax_modal').modal('hide');
$("#order_<%=@order.order_id%>").replaceWith('<%=j render :partial=>"order_tr",:locals=>{ :order=>@order }%>');

app/views/admin/orders/index.js.erb
$("#orders tbody").html('<%= j render(:partial=>"order_tr",:collection=>@orders,:as=>:order)%>');
$(".pagination").html('<%= j will_paginate(@orders,:container=>false)%>');
$("#orders").attr("data-url","<%=request.fullpath%>");
window.location.hash = "#page=<%=params[:page] || 1%>";

app/views/admin/orders/pay.html.erb
<div id="pay">
	<h4>支付 : <%=@order.order_id%></h4>
   	<hr>
	<%=render "pay_form"%>
</div>

app/views/admin/orders/print_order.html.erb
<h2 class="title">客户订单</h2>

<ul class="basic clearfix">
	<li>
		<span class="label">订单编号 : </span>	
		<span class="value"><%=@order.order_id%></span>
	</li>

	<li>
		<span class="label">订购时间 : </span>
		<span class="value"><%=@order.created_at%></span>
	</li>
	<li>
		<span class="label">收货人 : </span>
		<span class="value"><%=@order.ship_name%></span>
	</li>
	<li>
		<span class="label">联系方式 : </span>
		<span class="value"><%=@order.ship_mobile || @order.ship_tel%></span>
	</li>
	<li>
		<span class="label">支付方式 : </span>
		<span class="value"><%=@order.payment_name%></span>
	</li>
	<li>
		<span class="label">配送时间 : </span>
		<span class="value"><%=@order.ship_time%></span>
	</li>
	<li>
		<span class="label">收货地址 : </span>
		<span class="value"><%=@order.ship_addr%></span>
	</li>
	<li>
		<span class="label">邮政编码 : </span>
		<span class="value"><%=@order.ship_zip%></span>
	</li>
</ul>

<br>
<br>
<br>

<h3 class="title">订单详情</h3>

<table>
	<tr>
		<th>编号</th>
		<th>商品号</th>
		<th>商品名称</th>
		<th>商品单价</th>
		<th>数量</th>
		<th>小计</th>
	</tr>
	<%@order.order_items.each_with_index do |order_item,index|%>
	<tr>
		<td><%=index+1%></td>
		<td><%=order_item.bn%></td>
		<td><%=order_item.name%>(<%=order_item.product.spec_info%>)</td>
		<td>&yen;<%=order_item.price%></td>
		<td><%=order_item.nums.to_i%></td>
		<td>&yen;<%=order_item.amount.to_i%></td>
	</tr>
	<%end%>

	<tr>
		<td colspan="5" class="colspan">合计金额</td>
		<td>&yen;<%=@order.products_total.to_i%></td>
	</tr>
	<tr>
		<td colspan="5" class="colspan">运费</td>
		<td>&yen;<%=@order.cost_freight.to_i%></td>
	</tr>
	<tr>
		<td colspan="5" class="colspan">优惠金额</td>
		<td>&yen;<%=@order.pmts_total.to_i%></td>
	</tr>
	<tr>
		<td colspan="5" class="colspan">支付金额</td>
		<td>&yen;<%=@order.final_pay.to_i%></td>
	</tr>

</table>
<br>
<br>
<br>
<br>
<br>
<p>温馨提示 : </p>
<p class="indent">尊敬的会员：请您核对箱内商品信息与商品数量，如有疑问请致电scnc-sh上儿客服中心。</p>
<p class="indent">服务热线：021-37561067</p>
<p class="indent">E-Mail邮箱：cs@iotps.com</p>
<p class="indent">客服工作时间：每日 9 : 30~18 : 30（国家节假日除外）</p>
<script type="text/javascript">
	window.onload = function(){
		window.print()
	}
</script>

app/views/admin/orders/print_preparer.html.erb
<br>
<p class="large-title">订单调货（备货）凭证</p>

<span class="no">制单编号：CS - 20120821 - 001</span>
<span class="printer">打单员：</span>
<span class="date">日期：<%=Time.zone.now.strftime("%Y-%m-%d %H:%M:%S")%></span>
<table>
	<tr>
		<td>订单号</td>
		<td colspan="2"><%=@order.order_id%></td>
		<td >订单日期</td>
		<td colspan="2" style="width:190px;"><%=Time.at(@order.createtime).strftime("%Y-%m-%d")%></td>
		<td colspan="4">商务部/客服配合填写</td>
		<td colspan="3">(2次填写)商品入库时确认</td>
	</tr>
	<tr>
		<td>品牌名称</td>
		<td>商品编号	</td>
		<td>品牌商品编号</td>
		<td>商品名称</td>
		<td>数量</td>
		<td style="width:30px;">发票抬头</td>
		<td style="width:30px;">库存情况</td>
		<td style="width:30px;">订单状态</td>
		<td style="width:30px;">代理费率</td>
		<td style="width:30px;">快递公司</td>
		<td style="width:30px;">入库快递单号</td>
		<td style="width:30px;">快递费用</td>
		<td style="width:30px;">入库时间</td>
	</tr>
	<%@order.order_items.each do |order_item|%>
	<tr>
		<td><%=order_item.good.brand.brand_name if order_item.good.brand%></td>
		<td><%=order_item.bn%></td>
		<td></td>
		<td><%=order_item.name%>(<%=order_item.product.spec_info%>)</td>
		<td><%=order_item.nums.to_i%></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
		<td></td>
	</tr>
	<%end%>

	<tr>
		<td>资料核对</td>
		<td>发票 <input type="checkbox"></td>
		<td>赠品 <input type="checkbox"></td>
		<td colspan="10" style="text-align:left;padding-left:10px;">其他：</td>
	</tr>

	<tr>
		<td>订单备注</td>
		<td colspan="12"></td>
	</tr>
</table>
<p>流转说明 :</p>
<p class="pad">1. 客服制单打印“订单调货（备货）凭证”——晓晓 （同时电子文档发给晓晓，晓晓用于商品订单）</p>

<p class="pad">2. 晓晓电话品牌确认 有 无 并且在“电话确认”中备注后，交还——客服——更改订单状态
    <br>晓晓发出调配单给每个品牌 （可能会多张订单合并发出）</p>
<p class="pad">3. 品牌发货给晓晓，晓晓入库检验、整理，按订单通知 客服领取商品 （按先后订单领取）客服签收晓晓使用的验收文档，同时，晓晓完成此凭证项目，交回客服</p>


<script type="text/javascript">
	window.onload = function(){
		window.print()
	}
</script>